services:
  test: &base
    build:
      context: ./
      target: dev
    image: tuenti-test
    command: go test -v ./...
    volumes:
      - .:/go/src/github.com/michelsazevedo/tuenti/
      - go_build_cache:/root/.cache/go-build
    depends_on:
      - db
      - jaeger
      - kafka
      - redis
    stdin_open: true
    tty: true
    environment:
      - POSTGRES_USER=tuenti
      - POSTGRES_PASSWORD=tuentipwd
      - POSTGRES_DB=tuenti
      - POSTGRES_HOST=db:5432
      - ENV_APP=development
      - OTLP_ENDPOINT=jaeger:4318
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - KAFKA_BROKERS=kafka:9092
      - PASSWORD_RESET_BASE_URL=http://localhost:3000/reset-password
      - EMAIL_CONFIRMATION_BASE_URL=http://localhost:3000/confirm-email
      - INVITATION_BASE_URL=http://localhost:3000/invitations/accept

  web:
    <<: *base
    image: tuenti_web
    command: go run cmd/main.go
    ports:
      - "8080:8080"

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tuenti
      - POSTGRES_PASSWORD=tuentipwd
      - POSTGRES_DB=tuenti

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  kafka:
    image: apache/kafka:3.8.0
    restart: unless-stopped
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:29092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=CONTROLLER://:29093,PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      - CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  db_data:
  redis_data:
  go_build_cache:
