services:
  test: &base
    build:
      context: ./
      target: dev
    image: tuenti-test
    command: go test -v ./...
    volumes:
      - .:/go/src/github.com/michelsazevedo/tuenti/
      - go_build_cache:/root/.cache/go-build
    depends_on:
      - db
      - jaeger
      - redis
    stdin_open: true
    tty: true
    environment:
      - POSTGRES_USER=tuenti
      - POSTGRES_PASSWORD=tuentipwd
      - POSTGRES_DB=tuenti
      - POSTGRES_HOST=db:5432
      - ENV_APP=development
      - OTLP_ENDPOINT=jaeger:4318
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - RESEND_API_KEY=test-key
      - RESEND_FROM_EMAIL=test@example.com
      - PASSWORD_RESET_BASE_URL=http://localhost:3000/reset-password

  web:
    <<: *base
    image: tuenti_web
    command: go run cmd/main.go
    ports:
      - "8080:8080"

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tuenti
      - POSTGRES_PASSWORD=tuentipwd
      - POSTGRES_DB=tuenti

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  db_data:
  redis_data:
  go_build_cache:
