database:
  host: "${POSTGRES_HOST}"
  username: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  database: "${POSTGRES_DB}"
  timeout: 5s
  pool_size: 5

settings:
  secret: "YuDs1atWq3klVr2osUw8"
  application_name: husky
  environment: "${ENV_APP}"
  password_reset_base_url: "${PASSWORD_RESET_BASE_URL}"
  email_confirmation_base_url: "${EMAIL_CONFIRMATION_BASE_URL}"
  invitation_base_url: "${INVITATION_BASE_URL}"
  server:
    port: ":8080"

kafka:
  brokers: "${KAFKA_BROKERS}"

observability:
  otlp_endpoint: "${OTLP_ENDPOINT}"

redis:
  host: "${REDIS_HOST}"
  password: "${REDIS_PASSWORD}"
  db: 0

resend:
  api_key: "${RESEND_API_KEY}"
  from_email: "${RESEND_FROM_EMAIL}"
